apiVersion: v1
kind: Pod
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  containers:
  - name: myapp
    image: adarshraj73/demo-app:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  
